[package]
name = "scrolls"
edition = "2024.beta"
license = "Apache-2.0"
authors = ["Scrolls"]
version = "0.1.0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }

[addresses]
scrolls = "0x0"

[dev-dependencies]

[dev-addresses]
scrolls = "0x0"
